language: cpp

sudo: required

compiler: gcc

cache:
  directories:
    $HOME/spack
    $HOME/spack-packages
    $HOME/.spack

before_install:
  - sudo apt-get install -y build-essential gfortran environment-modules
  - sudo apt-get install -y --reinstall ca-certificates
  - sudo update-ca-certificates -f
  - cd $HOME/spack
  - git pull
  - export SPACK_ROOT=$HOME/spack
  - source $SPACK_ROOT/share/spack/setup-env.sh
  - cd $HOME/spack-packages
  - git pull
#  - spack repo add $HOME/spack-packages
  - spack install googletest +gmock
  - pip install --user cpp-coveralls
  - cd $TRAVIS_BUILD_DIR

script:
  - mkdir build
  - cd build
  - spack setup flowing@master
  - ./spconfig.py ..
  - make
  - ./foo

after_success:
  - coveralls --gcov-options '\-lp'
