language: cpp

sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get install build-essential software-properties-common -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install gcc-snapshot -y
  - sudo apt-get update
  - sudo apt-get install gcc-8 g++-8 -y
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 60 --slave /usr/bin/g++ g++ /usr/bin/g++-8
  - git clone https://github.com/spack/spack.git /tmp/spack
  - export SPACK_ROOT=/tmp/spack
  - source $SPACK_ROOT/share/spack/setup-env.sh
  - spack bootstrap
  - git clone https://github.com/f-sim/spack-packages.git /tmp/spack-packages
  - spack repo add /tmp/spack-packages

script:
  - mkdir build
  - cd build
  - spack setup flowing@master
