language: cpp

sudo: required

compiler:
  - gcc
  - clang

before_install:
  - git clone https://github.com/spack/spack.git /tmp/spack
  - export SPACK_ROOT=/tmp/spack
  - source $SPACK_ROOT/share/spack/setup-env.sh
  - spack bootstrap
  - spack install curl
  - spack load curl
  - git clone https://github.com/f-sim/spack-packages.git /tmp/spack-packages
  - spack repo add /tmp/spack-packages

script:
  - mkdir build
  - cd build
  - spack setup flowing@master
